spring:
  application:
    name: twitter-user-timeline
  output:
    ansi:
      enabled: ALWAYS    
#  cache:
#    type: redis
  data:
    mongodb:
      uri: mongodb://localhost:27017/twitter
  cloud:
    stream:
      function:
        definition:
          TweetConsumer
          #producer;processor;consumer
      kafka:
        binder:
          brokers: raspberry:9092
          replicationFactor: 1
      bindings:
        TweetConsumer-in-0:
          destination: tweets
  zipkin:
    base-url: http://raspberry:9411
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://raspberry:8761/eureka
    
  instance:
    prefer-ip-address: true
        
server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://raspberry:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  metrics:    
    distribution:
      percentiles-histogram:
        greeting: true
        http:
          server:            
            requests: true


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
      org:
        springframework:
          web:
            servlet:
              DispatcherServlet: DEBUG

