spring:
  application:
    name: twitter-gateway
  cloud:
    gateway:
      routes:
      - id: accounts_route
        uri: lb://twitter-accounts
        predicates:
        - Path=/account/**
      - id: feed_route
        uri: lb://twitter-feed
        predicates:
        - Path=/feed/**
      - id: user_timeline_route
        uri: lb://twitter-user-timeline
        predicates:
        - Path=/user-timeline/**
        
        
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://raspberry:8761/eureka
    