spring:
  application:
    name: twitter-feed
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://localhost:27017/twitter
  cloud:
    stream:
      source: tweetBinding-out-0
      kafka:
        binder:
          brokers: raspberry:9092
          replicationFactor: 1
      bindings:
        tweetBinding-out-0:
          destination: tweets
  zipkin:
    baseUrl: http://raspberry:9411/
  sleuth:
    async:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://raspberry:8761/eureka   
  instance:
    prefer-ip-address: true
             
server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"
